baseURL = "http://d.pikulev.org/"
languageCode = "en-US"
title = "My personal site"

[[menu.main]]
name                   = "About Me"
weight                 = -110
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "Github"
weight                 = -100
identifier             = "github"
url                    = "http://github.com/shikaku"

[[menu.main]]
name                   = "LinkedIn"
weight                 = -90
identifier             = "linkedin"
url                    = "https://www.linkedin.com/in/dpikulev-cv/"

[params]
author                 = "Denis Pikulev"
avatar                 = "img/avatar.jpg"
selfintro              = "Team lead / Senior Front-end Developer"
email                  = "pikulev.denis@gmail.com"
github                 = "//github.com/shikaku"
i18n_flags             = false
lang                   = "en"
cachebuster            = true
